
  // This file was autogenerated by dynamically running setEnv.ts and using dotenv for managing API key secrecy
  export const environment = {
    production: false,
    WEATHER_API_KEY: '1331433b676b453990c12026220502'
  };
